[package]
name = "datalog"
version = "0.1.0"
edition = "2021"
authors = ["Tim Müller"]
repository = "https://github.com/Lut99/datalog-rs"
description = "A simple Datalog^\\neg interpreter to support the language as discussed in the paper."


[[example]]
name = "interpreter"
path = "examples/interpreter.rs"
required-features = ["interpreter", "parser"]

[[example]]
name = "railroad"
path = "examples/railroad.rs"
required-features = ["railroad"]


[dependencies]
ast-toolkit-punctuated = { git = "https://github.com/Lut99/ast-toolkit-rs", branch = "snack" }
ast-toolkit-railroad = { git = "https://github.com/Lut99/ast-toolkit-rs", branch = "snack", features = ["derive"], optional = true }
ast-toolkit-snack = { git = "https://github.com/Lut99/ast-toolkit-rs", branch = "snack", features = ["derive", "punctuated"], optional = true }
ast-toolkit-span = { git = "https://github.com/Lut99/ast-toolkit-rs", branch = "snack" }
enum-debug = { git = "https://github.com/Lut99/enum-debug", features = ["derive"] }
indexmap = "2.6.0"
itertools = "0.13.0"
log = { version = "0.4.22", optional = true }
paste = "1.0.15"

datalog-macros = { path = "./macros", optional = true }


[dev-dependencies]
clap = { version = "4.5.21", features = ["derive"] }
console = "0.15.8"
error-trace = { git = "https://github.com/Lut99/error-trace-rs" }
humanlog = { git = "https://github.com/Lut99/humanlog-rs" }
log = "0.4.22"


[features]
default = []

interpreter = []
parser = ["dep:ast-toolkit-snack"]
reserialize = []

macros = ["dep:datalog-macros"]
log = ["dep:log"]
railroad = ["dep:ast-toolkit-railroad"]


[workspace]
resolver = "2"
members = ["./macros"]
